version: "3.7"
services: 
  mongo: 
    image: mongo:4.4
    restart: unless-stopped
    volumes:
        - ../local_db:/data/db
    ports: 
        - 27017:27017
    environment:
        MONGO_INITB_DATABASE: notebot
  mongo-express-api:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo